/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.project;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gerico
 */
public class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminForm
     */
    public AdminForm() {
        initComponents();
    }
    
    public void submitDatatoDatabase(){
        
        try{
            
            String url = "";
            
        } catch (Exception e){
            
        }
    }
    
    private void userRegister(String fname, String Lname, String Role, String username, String password) {
       Connection dbconn = MyConnection.connectDB();
        if(dbconn != null){
        try {
            PreparedStatement st = (PreparedStatement)
                    dbconn.prepareStatement("INSERT INTO the_app_user (fname,lname,role,username,password) VALUES(?,?,?,?,?)");
                    
            st.setString(1, fname);
            st.setString(2, Lname);
            st.setString(3, ComboBoxRole.getSelectedItem().toString());
            st.setString(4, username);
            st.setString(5, password);
            
            int res = st.executeUpdate();
            JOptionPane.showMessageDialog(this, "User data inserted", "Success", JOptionPane.INFORMATION_MESSAGE);
            dispose();
            
        } catch (SQLException ex) {
            Logger.getLogger(Yearbook_Info_System.class.getName()).log(Level.SEVERE, null, ex); 
            JOptionPane.showMessageDialog(null, ex, "Connection Error: Unable To Reach Databse", JOptionPane.ERROR_MESSAGE);
        }
        
        
        }else{
            System.out.println("The connection is not available");
        } 
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        LastName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ComboBoxRole = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        adminCreateAccount = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        CheckBoxTermsandConditions = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        ConfirmPassword = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        adminClose = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/project/Admin Form/user (3).png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 23, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("First Name");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 163, -1, -1));

        firstName.setBackground(new java.awt.Color(237, 235, 235));
        firstName.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        firstName.setForeground(new java.awt.Color(0, 0, 0));
        firstName.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 186, 328, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Last Name");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 219, -1, -1));

        LastName.setBackground(new java.awt.Color(237, 235, 235));
        LastName.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        LastName.setForeground(new java.awt.Color(0, 0, 0));
        LastName.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 242, 328, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Role");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 275, -1, -1));

        ComboBoxRole.setBackground(new java.awt.Color(88, 114, 140));
        ComboBoxRole.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ComboBoxRole.setForeground(new java.awt.Color(255, 255, 255));
        ComboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Editor-In-Chief", "Asst. Editor-In-Chief", "Plan Manager", "Circular Manager", "Lay-Out Artist", "Encoder", "Photographer" }));
        ComboBoxRole.setDoubleBuffered(true);
        jPanel3.add(ComboBoxRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 298, 328, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 338, -1, -1));

        Username.setBackground(new java.awt.Color(237, 235, 235));
        Username.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(0, 0, 0));
        Username.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 361, 328, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 394, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Confirm Password");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 394, -1, -1));

        adminCreateAccount.setBackground(new java.awt.Color(88, 114, 140));
        adminCreateAccount.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        adminCreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        adminCreateAccount.setText("Create account ");
        adminCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminCreateAccountActionPerformed(evt);
            }
        });
        jPanel3.add(adminCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 482, 314, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 462, 228, -1));

        CheckBoxTermsandConditions.setBackground(new java.awt.Color(44, 62, 80));
        CheckBoxTermsandConditions.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        CheckBoxTermsandConditions.setForeground(new java.awt.Color(255, 255, 255));
        CheckBoxTermsandConditions.setText(" I agree to be bound by the project \"Service Terms\"");
        jPanel3.add(CheckBoxTermsandConditions, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 523, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("See out \"Pricacy Policy\"  for more Information");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 548, -1, -1));

        Password.setBackground(new java.awt.Color(237, 235, 235));
        Password.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Password.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 417, 149, -1));

        ConfirmPassword.setBackground(new java.awt.Color(237, 235, 235));
        ConfirmPassword.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ConfirmPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.add(ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 417, 157, -1));

        jPanel4.setBackground(new java.awt.Color(88, 114, 140));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("B E  A  M E M B E R !");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 14, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOW REGISTER HERE ");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 60, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 49, 277, 5));

        adminClose.setBackground(new java.awt.Color(255, 51, 51));
        adminClose.setText("X");
        adminClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminCloseActionPerformed(evt);
            }
        });
        jPanel4.add(adminClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 2, -1, -1));

        jLabel11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel11MouseDragged(evt);
            }
        });
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 90));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adminCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminCreateAccountActionPerformed
       Dashboard db = new Dashboard();
        
        
        String fname = firstName.getText();
        String Lname = LastName.getText();
        String Role = ComboBoxRole.getActionCommand();
        String username = Username.getText();
        String password = Password.getText();
        String Cpassword = ConfirmPassword.getText();
       
        
        if (fname.isEmpty()){
            JOptionPane.showMessageDialog(null, "First Name can't be Empty");
        }
        else if (Lname.isEmpty()){
            JOptionPane.showMessageDialog(null, "Last Name can't be Empty");
        }
        else if(username.isEmpty()){
            JOptionPane.showMessageDialog(null, "You Should Enter your Username"); 
        }
        else if(password.isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter your Password"); 
        }
        else{
            
        
            
        Dashboard.yearbookAdmin.setText(firstName.getText()+" "+LastName.getText()+"\n");
           switch (ComboBoxRole.getSelectedIndex()) {
               case 0:
                   Dashboard.positionAdmin.setText("Editor-In-Chief");
                   break;
               case 1:
                   Dashboard.positionAdmin.setText("Asst. Editor-In-Chief");
                   break;
               case 2:
                   Dashboard.positionAdmin.setText("Plan Manager");
                   break;
               case 3:
                   Dashboard.positionAdmin.setText("Circular Manager");
                   break;
               case 4:
                   Dashboard.positionAdmin.setText("Lay-out Artist");
                   break;
               case 5:
                   Dashboard.positionAdmin.setText("Encoder");
                   break;
               case 6:
                   Dashboard.positionAdmin.setText("Photographer");
                   break;
               default:
                   break;
           }
        db.setVisible(true);
            
            if(CheckBoxTermsandConditions.isSelected()){
            if(Password.getText().equals(ConfirmPassword.getText())){
                userRegister(fname,Lname,Role,username,password);
                this.dispose();  
            }
            else{
                JOptionPane.showMessageDialog(null, "Password is Incorrect");
            }
       
        }
        else{
           JOptionPane.showMessageDialog(null, "Pls. agree of our terms and conditions");
           
       }
            
        }
               
        
         
        
        
    }//GEN-LAST:event_adminCreateAccountActionPerformed

    private void adminCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_adminCloseActionPerformed

    private void jLabel11MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseDragged
       int kordinatX = evt.getXOnScreen();
       int kordinatY = evt.getYOnScreen();
        
       this.setLocation(kordinatX, kordinatY);
        
    }//GEN-LAST:event_jLabel11MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxTermsandConditions;
    private javax.swing.JComboBox<String> ComboBoxRole;
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JTextField LastName;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Username;
    private javax.swing.JButton adminClose;
    private javax.swing.JButton adminCreateAccount;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
