/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.project;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static pkgfinal.project.Dashboard.planTable;
import static pkgfinal.project.Dashboard.studentCourse;
import static pkgfinal.project.EditForm.EditPic;

/**
 *
 * @author John Christopher
 */
public class Club extends javax.swing.JFrame {

    /**
     * Creates new form Club
     */
    public Club() {
        initComponents();
     Connect();
     FillComboBox();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    DefaultTableModel d;
    int i;
    
        public void Connect()
    {
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/yearbook_database","root", "");
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Club.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex, "Connection Error: Unable To Reach Databse", JOptionPane.ERROR_MESSAGE);
            System.out.println("Connection Error");
        }
        
    }
        
        
    public void FillComboBox(){
       

       try{
       pst = con.prepareStatement("SELECT * FROM club_management");
       rs = pst.executeQuery();
       
       int itemCount = studentClub.getItemCount();

        for(int i=1;i<itemCount;i++){
            studentClub.removeItemAt(1);
         }  
       
       
 
       while(rs.next()){

           studentClub.addItem(rs.getString("Clubs"));
 
       }
  
       } catch(SQLException ex){
           
         JOptionPane.showMessageDialog(null, ex);
       }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        createClub = new javax.swing.JButton();
        closeClub = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        clubLabel = new javax.swing.JLabel();
        nameClub = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        studentClub = new javax.swing.JComboBox<>();
        addCLUB = new javax.swing.JButton();
        RESET = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(155, 165, 156));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 4));

        createClub.setBackground(new java.awt.Color(102, 102, 102));
        createClub.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        createClub.setForeground(new java.awt.Color(255, 255, 255));
        createClub.setText("Create Club");
        createClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createClubActionPerformed(evt);
            }
        });

        closeClub.setBackground(new java.awt.Color(192, 57, 43));
        closeClub.setForeground(new java.awt.Color(255, 255, 255));
        closeClub.setText("X");
        closeClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeClubActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clubLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clubLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
        );

        nameClub.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        nameClub.setForeground(new java.awt.Color(255, 255, 255));
        nameClub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameClub.setText("( Name of Club )");
        nameClub.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student Club : ");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        studentClub.setBackground(new java.awt.Color(102, 102, 102));
        studentClub.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        studentClub.setForeground(new java.awt.Color(255, 255, 255));
        studentClub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Club" }));
        studentClub.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                studentClubItemStateChanged(evt);
            }
        });
        studentClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentClubActionPerformed(evt);
            }
        });

        addCLUB.setBackground(new java.awt.Color(34, 167, 240));
        addCLUB.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        addCLUB.setForeground(new java.awt.Color(255, 255, 255));
        addCLUB.setText("Add Club");
        addCLUB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCLUBActionPerformed(evt);
            }
        });

        RESET.setBackground(new java.awt.Color(206, 91, 8));
        RESET.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        RESET.setForeground(new java.awt.Color(255, 255, 255));
        RESET.setText("Reset");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createClub)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeClub))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameClub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(studentClub, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RESET, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCLUB, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createClub)
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameClub, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(studentClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(addCLUB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RESET)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(closeClub)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void studentClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentClubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentClubActionPerformed

    private void createClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createClubActionPerformed
        Club.closeClub.doClick();
        CreateClub open = new CreateClub();
        open.setVisible(true);
        
    }//GEN-LAST:event_createClubActionPerformed

    private void closeClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeClubActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeClubActionPerformed

    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
        studentClub.setSelectedIndex(0);
        clubLabel.setIcon(null);
    }//GEN-LAST:event_RESETActionPerformed

    private void addCLUBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCLUBActionPerformed
        if (studentClub.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Please Select a Club", "Error Selection", JOptionPane.ERROR_MESSAGE);
        }
        else{
            
 
         if (Dashboard.studentClubs.getText().isEmpty()){
             
          String Club = studentClub.getSelectedItem().toString();
          Dashboard.studentClubs.setText(Club);
          studentClub.setSelectedIndex(0);
          clubLabel.setIcon(null);
                 
         }  
         else{
              int result = JOptionPane.showConfirmDialog(null, "Do you want to add more clubs?", "Add Clubs", JOptionPane.YES_NO_OPTION);
              boolean yes, no;
              if (yes = (result == JOptionPane.YES_OPTION)){
              String MORECLUBS;
              MORECLUBS =  Dashboard.studentClubs.getText() + " | " + studentClub.getSelectedItem().toString();
              
              if (Dashboard.studentClubs.getText().isEmpty() == false){
             
              Dashboard.studentClubs.setText(MORECLUBS);
              studentClub.setSelectedIndex(0);
              clubLabel.setIcon(null);
              }
                     
         }  
              
         }

        }  
    }//GEN-LAST:event_addCLUBActionPerformed

    private void studentClubItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_studentClubItemStateChanged
        

         String name = studentClub.getSelectedItem().toString();
         nameClub.setText(name);
        
         try {
            

            pst = con.prepareStatement("SELECT * FROM club_management WHERE Clubs = ?");
            pst.setString(1, name);
            rs = pst.executeQuery();
            
            if (rs.next()){
                
            ImageIcon imIco = new ImageIcon(rs.getString("ClubAttachment"));
            
            //make image fit
            Image imFit = imIco.getImage();
            Image imgFit = imFit.getScaledInstance(clubLabel.getWidth(), clubLabel.getHeight(), Image.SCALE_SMOOTH);
            clubLabel.setIcon(new ImageIcon(imgFit));
            
            }

           
        } catch (SQLException ex) {
            Logger.getLogger(Club.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex, "Connection Error: Unable To Reach Databse", JOptionPane.ERROR_MESSAGE);
        } 
         
         
    }//GEN-LAST:event_studentClubItemStateChanged

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Club().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RESET;
    private javax.swing.JButton addCLUB;
    public static javax.swing.JButton closeClub;
    private javax.swing.JLabel clubLabel;
    private javax.swing.JButton createClub;
    public static javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nameClub;
    public static javax.swing.JComboBox<String> studentClub;
    // End of variables declaration//GEN-END:variables
}
