/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.project;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author John Christopher
 */
public class CreateClub extends javax.swing.JFrame {

    /**
     * Creates new form CreateClub
     */
    public CreateClub() {
        initComponents();
        Connect();
        clubAttachment.setEnabled(false);
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
        public void Connect()
    {
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/yearbook_database","root", "");
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PlanForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex, "Connection Error: Unable To Reach Databse", JOptionPane.ERROR_MESSAGE);
            System.out.println("Connection Error");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        insertPicture = new javax.swing.JButton();
        clubAttachment = new javax.swing.JTextField();
        CreateClubaddclub = new javax.swing.JButton();
        CreateClubreset = new javax.swing.JButton();
        ClubName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        clubDescription = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        closeCreate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(63, 83, 70));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 180, 160));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name of Club :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Attachment :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        insertPicture.setBackground(new java.awt.Color(240, 195, 60));
        insertPicture.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        insertPicture.setForeground(new java.awt.Color(255, 255, 255));
        insertPicture.setText("Insert Picture");
        insertPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertPictureActionPerformed(evt);
            }
        });
        jPanel1.add(insertPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 120, -1));

        clubAttachment.setBackground(new java.awt.Color(186, 189, 178));
        clubAttachment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clubAttachment.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jPanel1.add(clubAttachment, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 230, 20));

        CreateClubaddclub.setBackground(new java.awt.Color(34, 167, 240));
        CreateClubaddclub.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        CreateClubaddclub.setForeground(new java.awt.Color(255, 255, 255));
        CreateClubaddclub.setText("Add Club");
        CreateClubaddclub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateClubaddclubActionPerformed(evt);
            }
        });
        jPanel1.add(CreateClubaddclub, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 91, -1));

        CreateClubreset.setBackground(new java.awt.Color(206, 91, 8));
        CreateClubreset.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        CreateClubreset.setForeground(new java.awt.Color(255, 255, 255));
        CreateClubreset.setText("Reset");
        CreateClubreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateClubresetActionPerformed(evt);
            }
        });
        jPanel1.add(CreateClubreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 91, -1));

        ClubName.setBackground(new java.awt.Color(186, 189, 178));
        ClubName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ClubName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ClubName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClubNameActionPerformed(evt);
            }
        });
        jPanel1.add(ClubName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 230, 20));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Description :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        clubDescription.setBackground(new java.awt.Color(186, 189, 178));
        clubDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clubDescription.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jPanel1.add(clubDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 230, 20));

        jPanel3.setBackground(new java.awt.Color(155, 165, 156));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        closeCreate.setBackground(new java.awt.Color(192, 57, 43));
        closeCreate.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        closeCreate.setForeground(new java.awt.Color(255, 255, 255));
        closeCreate.setText("x");
        closeCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeCreateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/project/Add Club/fan-club.png"))); // NOI18N
        jLabel1.setText(" CREATE CLUB");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(closeCreate))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(closeCreate)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeCreateActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeCreateActionPerformed

    private void CreateClubresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateClubresetActionPerformed
        ClubName.setText("");
        clubDescription.setText("");
        clubAttachment.setText(null);
        label.setIcon(null);
    }//GEN-LAST:event_CreateClubresetActionPerformed

    private void CreateClubaddclubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateClubaddclubActionPerformed
        if (ClubName.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Name of Club is empty");
        }
        else if (clubDescription.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Description is empty");
        }
        

    try {
            
            pst = con.prepareStatement("INSERT INTO club_management(Clubs, Description, ClubAttachment) VALUES (?,?,?)");
            pst.setString(1,ClubName.getText());
            pst.setString(2,clubDescription.getText());
            pst.setString(3,clubAttachment.getText());
            
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Club Created");
        
            
        ClubName.setText("");
        clubDescription.setText("");
        clubAttachment.setText(null);
        label.setIcon(null);
        
        
        
                   
        } catch (SQLException ex) {
            Logger.getLogger(PlanForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex, "Connection Error: Unable To Reach Databse", JOptionPane.ERROR_MESSAGE);
        }  

    }//GEN-LAST:event_CreateClubaddclubActionPerformed

    private void insertPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertPictureActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("4 Extensions Supported", "jpg", "png", "jpeg", "gif");
        fileChooser.setFileFilter(filter);
        int selected = fileChooser.showOpenDialog(this);
        if(selected == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            String getselectedImage = file.getAbsolutePath();
            //JOptionPane.showMessageDialog(null, getselectedImage);
            ImageIcon imIco = new ImageIcon(getselectedImage);
            //make image fit
            Image imFit = imIco.getImage();
            Image imgFit = imFit.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
            label.setIcon(new ImageIcon(imgFit));
            
            clubAttachment.setText(getselectedImage);
        }
    }//GEN-LAST:event_insertPictureActionPerformed

    private void ClubNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClubNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClubNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateClub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ClubName;
    private javax.swing.JButton CreateClubaddclub;
    private javax.swing.JButton CreateClubreset;
    private javax.swing.JButton closeCreate;
    private javax.swing.JTextField clubAttachment;
    private javax.swing.JTextField clubDescription;
    private javax.swing.JButton insertPicture;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
