/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.project;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author John Christopher
 */
public class EditForm extends javax.swing.JFrame {

    /**
     * Creates new form EditForm
     */
    public EditForm() {
        initComponents();
        Connect();
        FillComboBox();
        idnumber.setEnabled(false);
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    DefaultTableModel d;
    
    String getselectedImage;
    
    
    public void Connect()
    {
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/yearbook_database","root", "");
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(EditForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex, "Connection Error: Unable To Reach Databse", JOptionPane.ERROR_MESSAGE);
            System.out.println("Connection Error");
        }
        
    }
    
    public void FillComboBox(){
       

       try{
       pst = con.prepareStatement("SELECT * FROM section_management");
       rs = pst.executeQuery();
       
       int itemCount = yearlevel.getItemCount();

        for(int i=1;i<itemCount;i++){
            yearlevel.removeItemAt(1);
         } 
   
       while(rs.next()){

           yearlevel.addItem(rs.getString("Courses"));
      
       }
  
       } catch(SQLException ex){
         JOptionPane.showMessageDialog(null, ex, "Connection Error: Unable To Reach Databse", JOptionPane.ERROR_MESSAGE); 
       }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        EditPic = new javax.swing.JLabel();
        editProfile = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        mname = new javax.swing.JTextField();
        sname = new javax.swing.JTextField();
        extension = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        idnumber = new javax.swing.JTextField();
        yearlevel = new javax.swing.JComboBox<>();
        email = new javax.swing.JTextField();
        mobilenum = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        editClubs = new javax.swing.JTextField();
        qt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        graduated = new javax.swing.JComboBox<>();
        HonorStudent = new javax.swing.JComboBox<>();
        YearbookPaid = new javax.swing.JComboBox<>();
        editClear = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        BIRTHdate = new com.toedter.calendar.JDateChooser();
        FILEPATH = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        editRefresh = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        soli = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        closeEditForm = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(172, 52, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EditPic, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EditPic, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 30, -1, -1));

        editProfile.setBackground(new java.awt.Color(255, 204, 0));
        editProfile.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        editProfile.setForeground(new java.awt.Color(255, 255, 255));
        editProfile.setText("Edit Profile");
        editProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileActionPerformed(evt);
            }
        });
        jPanel1.add(editProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 132, 112, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 31, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Middle Name :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 62, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Surname :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 93, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Extensions :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 124, -1, -1));

        fname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fname.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 30, 205, -1));

        mname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 61, 205, -1));

        sname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 92, 205, -1));

        extension.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(extension, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 123, 205, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID Number :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Student Course:");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Contact Number : ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Birthdate :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Address :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Solicitation :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Clubs :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        idnumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        idnumber.setForeground(new java.awt.Color(0, 0, 0));
        idnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idnumberActionPerformed(evt);
            }
        });
        idnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idnumberKeyTyped(evt);
            }
        });
        jPanel1.add(idnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 110, -1));

        yearlevel.setBackground(new java.awt.Color(217, 83, 25));
        yearlevel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        yearlevel.setForeground(new java.awt.Color(255, 255, 255));
        yearlevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Course" }));
        jPanel1.add(yearlevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 337, -1));

        email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        email.setForeground(new java.awt.Color(0, 0, 0));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 283, 337, -1));

        mobilenum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mobilenum.setForeground(new java.awt.Color(0, 0, 0));
        mobilenum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilenumActionPerformed(evt);
            }
        });
        mobilenum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobilenumKeyTyped(evt);
            }
        });
        jPanel1.add(mobilenum, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 320, 337, -1));

        address.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        address.setForeground(new java.awt.Color(0, 0, 0));
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 392, 337, -1));

        editClubs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        editClubs.setForeground(new java.awt.Color(0, 0, 0));
        editClubs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editClubsKeyTyped(evt);
            }
        });
        jPanel1.add(editClubs, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 337, -1));

        qt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        qt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(qt, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 466, 337, 60));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/project/Pictures/Picture107.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/project/Pictures/Picture108.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/project/Pictures/Picture106.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, -1, 38));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("GRADUATED :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 600, -1, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("HONOR STUDENT : ");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 660, -1, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("YEARBOOK PAID :");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 720, -1, -1));

        graduated.setBackground(new java.awt.Color(217, 83, 25));
        graduated.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        graduated.setForeground(new java.awt.Color(255, 255, 255));
        graduated.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TBD", "YES", "NO" }));
        jPanel1.add(graduated, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 590, 81, -1));

        HonorStudent.setBackground(new java.awt.Color(217, 83, 25));
        HonorStudent.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        HonorStudent.setForeground(new java.awt.Color(255, 255, 255));
        HonorStudent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TBD", "YES", "NO" }));
        jPanel1.add(HonorStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 650, 81, -1));

        YearbookPaid.setBackground(new java.awt.Color(217, 83, 25));
        YearbookPaid.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        YearbookPaid.setForeground(new java.awt.Color(255, 255, 255));
        YearbookPaid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TBD", "YES", "NO" }));
        jPanel1.add(YearbookPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 710, 81, -1));

        editClear.setBackground(new java.awt.Color(255, 51, 0));
        editClear.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        editClear.setForeground(new java.awt.Color(255, 255, 255));
        editClear.setText("Clear Form");
        editClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editClearActionPerformed(evt);
            }
        });
        jPanel1.add(editClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 630, 106, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("PROFILE");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 8, -1, 16));

        BIRTHdate.setDateFormatString("MM/dd/yy");
        BIRTHdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(BIRTHdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 357, 178, -1));

        FILEPATH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FILEPATH.setForeground(new java.awt.Color(0, 0, 0));
        FILEPATH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FILEPATHActionPerformed(evt);
            }
        });
        FILEPATH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FILEPATHKeyTyped(evt);
            }
        });
        jPanel1.add(FILEPATH, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 175, 337, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("File Path:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        editRefresh.setBackground(new java.awt.Color(51, 51, 255));
        editRefresh.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        editRefresh.setForeground(new java.awt.Color(255, 255, 255));
        editRefresh.setText("Refresh");
        editRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(editRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 680, 106, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Quote :");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        soli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        soli.setForeground(new java.awt.Color(0, 0, 0));
        soli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soliKeyTyped(evt);
            }
        });
        jPanel1.add(soli, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 429, 337, -1));

        jPanel2.setBackground(new java.awt.Color(217, 83, 25));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.setPreferredSize(new java.awt.Dimension(482, 78));
        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/project/Edit Form/editForm.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(160, 10, 30, 70);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EDIT FORM ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(200, 30, 128, 31);

        closeEditForm.setBackground(new java.awt.Color(255, 51, 51));
        closeEditForm.setText("X");
        closeEditForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeEditFormActionPerformed(evt);
            }
        });
        jPanel2.add(closeEditForm);
        closeEditForm.setBounds(430, 0, 50, 30);

        jLabel23.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel23MouseDragged(evt);
            }
        });
        jPanel2.add(jLabel23);
        jLabel23.setBounds(0, 0, 480, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeEditFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeEditFormActionPerformed
       this.dispose();
    }//GEN-LAST:event_closeEditFormActionPerformed

    private void editClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editClearActionPerformed

        fname.setText("");
        mname.setText("");
        sname.setText("");
        extension.setText("");
        idnumber.setText("");
        yearlevel.setSelectedIndex(0);
        email.setText("");
        mobilenum.setText("");
        BIRTHdate.setDate(null);
        address.setText("");
        editClubs.setText("");
        qt.setText("");
        editClubs.setText("");
        graduated.setSelectedIndex(0);
        HonorStudent.setSelectedIndex(0);
        YearbookPaid.setSelectedIndex(0);
    }//GEN-LAST:event_editClearActionPerformed

    private void editClubsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editClubsKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_editClubsKeyTyped

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void mobilenumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobilenumKeyTyped
        char b = evt.getKeyChar();

        if (!Character.isDigit(b)){
            evt.consume();
        }
    }//GEN-LAST:event_mobilenumKeyTyped

    private void mobilenumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilenumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobilenumActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void idnumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idnumberKeyTyped
        char a = evt.getKeyChar();

        if (!Character.isDigit(a)){
            evt.consume();
        }
    }//GEN-LAST:event_idnumberKeyTyped

    private void idnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idnumberActionPerformed

    }//GEN-LAST:event_idnumberActionPerformed

    private void editProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("4 Extensions Supported", "jpg", "png", "jpeg", "gif");
        fileChooser.setFileFilter(filter);
        int selected = fileChooser.showOpenDialog(this);
        if(selected == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            getselectedImage = file.getAbsolutePath();
            //JOptionPane.showMessageDialog(null, getselectedImage);
            ImageIcon imIco = new ImageIcon(getselectedImage);
            //make image fit
            Image imFit = imIco.getImage();
            Image imgFit = imFit.getScaledInstance(EditPic.getWidth(), EditPic.getHeight(), Image.SCALE_SMOOTH);
            EditPic.setIcon(new ImageIcon(imgFit));
            FILEPATH.setText(getselectedImage);
        }

    }//GEN-LAST:event_editProfileActionPerformed

    private void jLabel23MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseDragged
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();

        this.setLocation(kordinatX, kordinatY);
    }//GEN-LAST:event_jLabel23MouseDragged

    private void FILEPATHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FILEPATHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FILEPATHActionPerformed

    private void FILEPATHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FILEPATHKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_FILEPATHKeyTyped

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
      
    }//GEN-LAST:event_jLabel8MouseClicked

    private void editRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRefreshActionPerformed
        FillComboBox();
    }//GEN-LAST:event_editRefreshActionPerformed

    private void soliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soliKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_soliKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static com.toedter.calendar.JDateChooser BIRTHdate;
    public static javax.swing.JLabel EditPic;
    public static javax.swing.JTextField FILEPATH;
    public static javax.swing.JComboBox<String> HonorStudent;
    public static javax.swing.JComboBox<String> YearbookPaid;
    public static javax.swing.JTextField address;
    public static javax.swing.JButton closeEditForm;
    private javax.swing.JButton editClear;
    public static javax.swing.JTextField editClubs;
    private javax.swing.JButton editProfile;
    private javax.swing.JButton editRefresh;
    public static javax.swing.JTextField email;
    public static javax.swing.JTextField extension;
    public static javax.swing.JTextField fname;
    public static javax.swing.JComboBox<String> graduated;
    public static javax.swing.JTextField idnumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JTextField mname;
    public static javax.swing.JTextField mobilenum;
    public static javax.swing.JTextField qt;
    public static javax.swing.JTextField sname;
    public static javax.swing.JTextField soli;
    public static javax.swing.JComboBox<String> yearlevel;
    // End of variables declaration//GEN-END:variables
}
