/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.project;

import java.util.Date;


/**
 *
 * @author John Christopher
 */
public class PrintReceipt extends javax.swing.JFrame {

    /**
     * Creates new form PrintReceipt
     */
    public PrintReceipt() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.toFront();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        IDNUM = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        TOTALDUE = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        MONEY = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        PAIDSTATUS = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        ISSUEDTO = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CHANGE = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        closeReceipt = new javax.swing.JButton();
        DATE = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/project/Print Receipt/Picture3.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 32, 134, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("YEARBOOK RECEIPT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 74, 308, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("---------------------------------------------");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 185, 454, 30));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ID Number : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 233, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Total Due :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 273, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Change :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Amount Paid :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Issued To : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Date :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        IDNUM.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        IDNUM.setForeground(new java.awt.Color(0, 0, 0));
        IDNUM.setBorder(null);
        IDNUM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        IDNUM.setOpaque(false);
        jPanel1.add(IDNUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 233, 140, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 258, 140, 9));

        TOTALDUE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        TOTALDUE.setForeground(new java.awt.Color(0, 0, 0));
        TOTALDUE.setBorder(null);
        TOTALDUE.setOpaque(false);
        jPanel1.add(TOTALDUE, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 273, 140, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 298, 140, 11));

        MONEY.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        MONEY.setForeground(new java.awt.Color(0, 0, 0));
        MONEY.setBorder(null);
        MONEY.setOpaque(false);
        MONEY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MONEYMouseClicked(evt);
            }
        });
        MONEY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MONEYActionPerformed(evt);
            }
        });
        jPanel1.add(MONEY, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 89, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 89, 10));

        PAIDSTATUS.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        PAIDSTATUS.setForeground(new java.awt.Color(0, 0, 0));
        PAIDSTATUS.setBorder(null);
        PAIDSTATUS.setOpaque(false);
        PAIDSTATUS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PAIDSTATUSMouseClicked(evt);
            }
        });
        PAIDSTATUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAIDSTATUSActionPerformed(evt);
            }
        });
        jPanel1.add(PAIDSTATUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 315, 140, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 340, 140, 11));

        ISSUEDTO.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ISSUEDTO.setForeground(new java.awt.Color(0, 0, 0));
        ISSUEDTO.setBorder(null);
        ISSUEDTO.setOpaque(false);
        jPanel1.add(ISSUEDTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 353, 140, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 378, 140, 10));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("----------------------------------------------");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 406, -1, 17));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("THANK YOU!");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 508, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/project/Print Receipt/paid (1).png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 435, -1, 70));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Amount :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        CHANGE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CHANGE.setForeground(new java.awt.Color(0, 0, 0));
        CHANGE.setBorder(null);
        CHANGE.setOpaque(false);
        CHANGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHANGEActionPerformed(evt);
            }
        });
        jPanel1.add(CHANGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 89, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 370, 110, 10));

        closeReceipt.setBackground(new java.awt.Color(51, 51, 51));
        closeReceipt.setForeground(new java.awt.Color(255, 255, 255));
        closeReceipt.setText("X");
        closeReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeReceiptActionPerformed(evt);
            }
        });
        jPanel1.add(closeReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, -1));

        DATE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DATE.setForeground(new java.awt.Color(0, 0, 0));
        DATE.setBorder(null);
        DATE.setOpaque(false);
        DATE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DATEMouseClicked(evt);
            }
        });
        DATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DATEActionPerformed(evt);
            }
        });
        jPanel1.add(DATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 350, 110, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 89, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MONEYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MONEYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MONEYActionPerformed

    private void PAIDSTATUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAIDSTATUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PAIDSTATUSActionPerformed

    private void CHANGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHANGEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHANGEActionPerformed

    private void MONEYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MONEYMouseClicked
       MONEY.setText(null);
    }//GEN-LAST:event_MONEYMouseClicked

    private void PAIDSTATUSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAIDSTATUSMouseClicked
      PAIDSTATUS.setText(null);
    }//GEN-LAST:event_PAIDSTATUSMouseClicked

    private void closeReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeReceiptActionPerformed
       this.dispose();
       Dashboard.printButton.setEnabled(true);
    }//GEN-LAST:event_closeReceiptActionPerformed

    private void DATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DATEActionPerformed
        
  
    }//GEN-LAST:event_DATEActionPerformed

    private void DATEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DATEMouseClicked
        Date obj = new Date();
        String date = obj.toString();
        DATE.setText(date);
    }//GEN-LAST:event_DATEMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField CHANGE;
    public static javax.swing.JTextField DATE;
    public static javax.swing.JTextField IDNUM;
    public static javax.swing.JTextField ISSUEDTO;
    public static javax.swing.JTextField MONEY;
    public static javax.swing.JTextField PAIDSTATUS;
    public static javax.swing.JTextField TOTALDUE;
    public static javax.swing.JButton closeReceipt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
