/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.project;

import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;

/**
 *
 * @author John Christopher
 */
public class SectionForm extends javax.swing.JFrame {

    /**
     * Creates new form SectionForm
     */
    public SectionForm() {
        initComponents();
        Connect();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
     public void Connect()
    {
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/yearbook_database","root", "");
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PlanForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex, "Connection Error: Unable To Reach Databse", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addCourseAdd = new javax.swing.JButton();
        addCourseReset = new javax.swing.JButton();
        studentCourse = new javax.swing.JTextField();
        batchYear = new javax.swing.JTextField();
        students = new javax.swing.JTextField();
        addCourseclose = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(68, 66, 110));
        jPanel1.setPreferredSize(new java.awt.Dimension(326, 343));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Course Form ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/project/Add Section Form/add (2).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 21, -1, 74));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student Course:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 36));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Batch Year:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 110, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Number of Students :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 19));

        addCourseAdd.setBackground(new java.awt.Color(34, 167, 240));
        addCourseAdd.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        addCourseAdd.setForeground(new java.awt.Color(255, 255, 255));
        addCourseAdd.setText("Add");
        addCourseAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseAddActionPerformed(evt);
            }
        });
        jPanel1.add(addCourseAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 66, -1));

        addCourseReset.setBackground(new java.awt.Color(255, 204, 0));
        addCourseReset.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        addCourseReset.setForeground(new java.awt.Color(255, 255, 255));
        addCourseReset.setText("Reset");
        addCourseReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseResetActionPerformed(evt);
            }
        });
        jPanel1.add(addCourseReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        studentCourse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        studentCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentCourseActionPerformed(evt);
            }
        });
        jPanel1.add(studentCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 150, -1));

        batchYear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(batchYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 150, -1));

        students.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(students, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 150, -1));

        addCourseclose.setBackground(new java.awt.Color(255, 51, 51));
        addCourseclose.setForeground(new java.awt.Color(255, 255, 255));
        addCourseclose.setText("X");
        addCourseclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCoursecloseActionPerformed(evt);
            }
        });
        jPanel1.add(addCourseclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 0, -1, -1));

        jLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel6MouseDragged(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addCourseAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseAddActionPerformed
       
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(  
         "Century Gothic", Font.BOLD, 14)));
        
        JOptionPane.showConfirmDialog(this,"Section Number : " + studentCourse.getText()
                                        + "\nCourse : " + batchYear.getText()
                                        + "\nStudents : " + students.getText(),"Do you want to continue?", JOptionPane.YES_NO_OPTION);
        
        try{
           pst = con.prepareStatement("INSERT INTO section_management(Courses, BatchYear, Students) VALUES (?,?,?)");
           pst.setString(1,studentCourse.getText() + " " + ("Year - " + batchYear.getText()));
           pst.setString(2,batchYear.getText());
           pst.setString(3,students.getText());
           
           pst.executeUpdate();
           JOptionPane.showMessageDialog(this, "Course Added");
           this.dispose();
           
           
        } catch (SQLException ex) {
            Logger.getLogger(SectionForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex, "Connection Error: Unable To Reach Databse", JOptionPane.ERROR_MESSAGE);
        } 
        
        
    }//GEN-LAST:event_addCourseAddActionPerformed

    private void studentCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentCourseActionPerformed

    private void addCourseResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseResetActionPerformed
        studentCourse.setText(" ");
        batchYear.setText(" ");
        students.setText(" ");
    }//GEN-LAST:event_addCourseResetActionPerformed

    private void addCoursecloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCoursecloseActionPerformed
       this.dispose();
    }//GEN-LAST:event_addCoursecloseActionPerformed

    private void jLabel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseDragged
       int kordinatX = evt.getXOnScreen();
       int kordinatY = evt.getYOnScreen();
        
       this.setLocation(kordinatX, kordinatY);
    }//GEN-LAST:event_jLabel6MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SectionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourseAdd;
    private javax.swing.JButton addCourseReset;
    private javax.swing.JButton addCourseclose;
    private javax.swing.JTextField batchYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField studentCourse;
    private javax.swing.JTextField students;
    // End of variables declaration//GEN-END:variables
}
